# Generated by Django 4.1.7 on 2024-10-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment_management', '0001_initial'),
        ('api_management', '0002_alter_apiinterface_request_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='测试用例名称')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=20, verbose_name='请求方法')),
                ('url', models.URLField(verbose_name='接口地址')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='请求头')),
                ('body', models.TextField(blank=True, verbose_name='Request Body')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('request_data', models.JSONField(verbose_name='请求参数')),
                ('expected_response', models.JSONField(verbose_name='期望结果')),
                ('extract_var', models.CharField(blank=True, max_length=1024, null=True, verbose_name='关联参数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(help_text='0:表示有效，1:表示无效', null=True)),
                ('is_executed', models.BooleanField(default=False, verbose_name='是否执行')),
                ('is_smoke', models.BooleanField(default=False, verbose_name='是否冒烟')),
                ('is_reback', models.BooleanField(default=False, verbose_name='是否回归')),
                ('execute_result', models.CharField(max_length=1024, null=True, verbose_name='执行结果')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('host_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment_management.environment', verbose_name='host地址')),
                ('relate_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_management.apiinterface', verbose_name='关联接口')),
            ],
            options={
                'verbose_name': '测试用例表',
                'verbose_name_plural': '测试用例表',
            },
        ),
    ]
