# Generated by Django 4.1.7 on 2024-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_case_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='接口地址'),
        ),
    ]
