# Generated by Django 4.1.7 on 2024-10-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testscenario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', '成功'), ('fail', '失败'), ('running', '运行中')], max_length=50)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.CharField(blank=True, max_length=255, null=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testscenario.testscenario')),
            ],
            options={
                'verbose_name': '测试结果表',
                'verbose_name_plural': '测试结果表',
            },
        ),
    ]
