# Generated by Django 4.1.7 on 2024-09-23 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0001_initial'),
        ('module_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='接口名称')),
                ('url', models.URLField(verbose_name='接口地址')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='请求头')),
                ('request_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=6, verbose_name='请求方式')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用'), ('maintenance', '维护中')], max_length=20, verbose_name='状态')),
                ('request_params', models.JSONField(blank=True, null=True, verbose_name='入参')),
                ('response_params', models.JSONField(blank=True, null=True, verbose_name='出参')),
                ('desc', models.TextField(max_length=2000, verbose_name='简要描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_management.module', verbose_name='所属模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口管理',
                'verbose_name_plural': '接口管理表',
            },
        ),
    ]
