# Generated by Django 4.1.7 on 2024-09-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinterface',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=20, verbose_name='请求方式'),
        ),
    ]
