# Generated by Django 4.1.7 on 2024-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_management', '0002_alter_apiinterface_request_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinterface',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='接口地址'),
        ),
    ]
