# Generated by Django 4.1.7 on 2024-10-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_case_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('test_cases', models.ManyToManyField(related_name='scenarios', to='test_case_management.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试场景表',
                'verbose_name_plural': '测试场景表',
            },
        ),
    ]
