# Generated by Django 4.1.7 on 2024-10-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testscenario', '0001_initial'),
        ('scheduled_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='testscenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testscenario.testscenario', verbose_name='测试场景'),
        ),
    ]
