# Generated by Django 4.1.7 on 2024-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testscenario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('scenarios', models.ManyToManyField(related_name='plans', to='testscenario.testscenario')),
            ],
            options={
                'verbose_name': '测试计划表',
                'verbose_name_plural': '测试计划表',
            },
        ),
    ]
